spring:
  mail:
    host: smtp.163.com
    username: mr_blw163@163.com
    password: 122800blw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
